






#ifndef WIDGETCNPMETORTOTP_GLOBAL_H
#define WIDGETCNPMETORTOTP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CNPMETORTOTP_LIBRARY)
#  define  WIDGETCNPMETORTOTP_EXPORT Q_DECL_EXPORT
#else
#  define  WIDGETCNPMETORTOTP_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETCNPMETORTOTP_GLOBAL_H
