#ifndef REGISTROTP_GLOBAL_H
#define REGISTROTP_GLOBAL_H

#include <QtCore/qglobal.h>


#if defined(REGISTROTP_LIBRARY)
#  define REGISTROTP_EXPORT Q_DECL_EXPORT
#else
#  define REGISTROTP_EXPORT Q_DECL_IMPORT
#endif

#endif // REGISTROTP_GLOBAL_H
