#ifndef COORDINATESTP_GLOBAL_H
#define COORDINATESTP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COORDINATESTP_LIBRARY)
#  define COORDINATESTPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COORDINATESTPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COORDINATESTP_GLOBAL_H
