#ifndef CONTROLOPETP_GLOBAL_H
#define CONTROLOPETP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLOPETP_LIBRARY)
#  define CONTROLOPETPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLOPETPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLOPETP_GLOBAL_H
