#ifndef OPERACIONPCOT_GLOBAL_H
#define OPERACIONPCOT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPERACIONPCOT_LIBRARY)
#  define OPERACIONPCOTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPERACIONPCOTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPERACIONPCOT_GLOBAL_H
