#ifndef WIDGETPROYECTOTP_GLOBAL_H
#define WIDGETPROYECTOTP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETPROYECTOTP_LIBRARY)
#  define WIDGETPROYECTOTPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIDGETPROYECTOTPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETPROYECTOTP_GLOBAL_H
