#ifndef COMPONENTESTP_GLOBAL_H
#define COMPONENTESTP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPONENTESTP_LIBRARY)
#  define COMPONENTESTPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPONENTESTPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPONENTESTP_GLOBAL_H
