#ifndef REGISTROCNPMETORTO_GLOBAL_H
#define REGISTROCNPMETORTO_GLOBAL_H

#include <QtCore/qglobal.h>


#if defined(REGISTROCNPMETORTOTP_LIBRARY)
#  define REGISTROCNPMETORTOTP_EXPORT Q_DECL_EXPORT
#else
#  define REGISTROCNPMETORTOTP_EXPORT Q_DECL_IMPORT
#endif

#endif // REGISTROCNPMETORTOTP_GLOBAL_H
