#ifndef REGISTROCNPMETORTO_GLOBAL_H
#define REGISTROCNPMETORTO_GLOBAL_H

#include <QtCore/qglobal.h>


#if defined(REGISTROCNPMETORTO_LIBRARY)
#  define REGISTROCNPMETORTO_EXPORT Q_DECL_EXPORT
#else
#  define REGISTROCNPMETORTO_EXPORT Q_DECL_IMPORT
#endif

#endif // REGISTROCNPMETORTO_GLOBAL_H
