#ifndef WIDGETCOORDINATESTP_GLOBAL_H
#define WIDGETCOORDINATESTP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETCOORDINATESTP_LIBRARY)
#  define WIDGETCOORDINATESTPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIDGETCOORDINATESTPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETCOORDINATESTP_GLOBAL_H
